# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  user_token:  # user token from text.ru
    description: 'User token'
    required: true
outputs:
  uniq: # uniq text percent
    description: 'Text uniq'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user_token }}